backend:
  name: git-gateway
  repo: yfjiang-danny/online-editor # your GitHub username and repository name
  branch: main
  # base_url: /.netlify/git/yfjiang-danny/online-editor
  # api_root: https://gitlab.com/api/v4

# This line should *not* be indented
publish_mode: editorial_workflow

# Media files will be stored in the repo under images/uploads
media_folder: "static/assets/uploads"
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/assets/uploads"

collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Title" }
